### ISSUE TITLE
Add a project description to README.md to explain what this is

### ISSUE THREAD

**Issue by henrebotha** [dezmathio/underarmour#25]
I came across this project via Hacktoberfest, but was immediately stymied by the lack of explanation of what this is.

I realise I can click through to the website, but I think an open source project should have a concise explanation in the repo itself. This would make it easier for others to contribute.

**Comment by dezmathio** [comment]
ok @henrebotha I added this for you https://github.com/dezmathio/underarmour/commit/447d5b5bd942f4391b90d75e508384b80e3cf4bc

Let me know if that clears up any confusion
