### ISSUE TITLE
Create some very rudimentary baseline tests

### ISSUE THREAD

**Issue by dezmathio** [dezmathio/underarmour#3]

**Comment by gURLmeetsCode** [comment]
@dezmathio Hey, I would love to help out! I do not see your core logic but I can try to set up some test templates for you.

**Comment by dezmathio** [comment]
hey @gURLmeetsCode! Appreciate the help. I've got a PR right now setting up some modules that we could begin testing.

**Comment by gURLmeetsCode** [comment]
Sounds good.
