### ISSUE TITLE
create base client & api client, an example resource & spec

### ISSUE THREAD

**Issue by dezmathio** [dezmathio/underarmour#7]
as title indicates, create BaseClient, ApiClient, a User resource, and add to the tests so that we can verify this is working somewhat.

**Comment by paulohtfs** [comment]
Hello
This gem uses the [Under Armour API](https://developer.underarmour.com/)?
I wold like to help with that. Waiting for your PR to be merged to see the logic.

**Comment by dezmathio** [comment]
hey @paulohtfs that's the plan... it's still in the very early stages lol.

**Comment by dezmathio** [comment]
check it out now paulo. you'll need a api key/secret from them, & then authorize on your machine & get an access token to pass to the app for this to work. I'll work on writing up a small guide for that as well
